### ISSUE TITLE
Unable to run Docker image

### ISSUE THREAD

**Issue by R0manich** [BUILT-CoLAB/license-key-manager#24]
Hi, 
I'm trying to run the image in Docker but receiving the following error:

`Traceback (most recent call last):
  File "/home/appuser/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3112, in _wrap_pool_connect
    return fn()
  File "/home/appuser/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/appuser/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 748, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/appuser/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/appuser/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 259, in _do_get
    return self._create_connection()
  File "/home/appuser/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/appuser/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/appuser/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 597, in __connect
    with util.safe_reraise():
  File "/home/appuser/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/appuser/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 198, in raise_
    raise exception
  File "/home/appuser/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 592, in __connect
    connection = pool._invoke_creator(self)
  File "/home/appuser/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 576, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/appuser/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 548, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 231, in run
    super().run()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 58, in __init__
    self.setup(app)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 118, in setup
    self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 412, in import_app
    app = app(*args, **kwargs)
  File "/license-manager/bin/__init__.py", line 48, in create_app
    db.create_all(app=app)
  File "/home/appuser/.local/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1094, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/home/appuser/.local/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 1086, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/home/appuser/.local/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 4741, in create_all
    bind._run_ddl_visitor(
  File "/home/appuser/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2978, in _run_ddl_visitor
    with self.begin() as conn:
  File "/home/appuser/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2894, in begin
    conn = self.connect(close_with_result=close_with_result)
  File "/home/appuser/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3066, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/appuser/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 91, in __init__
    else engine.raw_connection()
  File "/home/appuser/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3145, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/appuser/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3115, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/appuser/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2003, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/appuser/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 198, in raise_
    raise exception
  File "/home/appuser/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3112, in _wrap_pool_connect
    return fn()
  File "/home/appuser/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 301, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/appuser/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 748, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/appuser/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 419, in checkout
    rec = pool._do_get()
  File "/home/appuser/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 259, in _do_get
    return self._create_connection()
  File "/home/appuser/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 247, in _create_connection
    return _ConnectionRecord(self)
  File "/home/appuser/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 362, in __init__
    self.__connect(first_connect_check=True)
  File "/home/appuser/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 597, in __connect
    with util.safe_reraise():
  File "/home/appuser/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/appuser/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 198, in raise_
    raise exception
  File "/home/appuser/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 592, in __connect
    connection = pool._invoke_creator(self)
  File "/home/appuser/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 576, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/appuser/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 548, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: http://sqlalche.me/e/14/e3q8)`

**Comment by jpdias** [comment]
Hey @R0manich, that's a know issue due to the permissions required by SQLite being incorrectly defined.  Please ensure that there exists a `database` named folder inside the `src/`. If you have any issues you can also force the correct permissions using `chmod` on a Linux machine. If you're on Windows, please use the latest version of Docker desktop.

**Comment by R0manich** [comment]
Hi @jpdias,
Thank you for your help! The solution is to add a _database_ named folder inside the _src/_.
